### ISSUE TITLE
[Feature Request] Video callback

### ISSUE THREAD

**Issue by pontakornth** [core-player/vue-core-video-player#16]
Actually it's simple callback for some event like video end, pausing. I think it will make this package suitable for some application like e-learning.

**Comment by JackPu** [comment]
@pontakornth  now you can use

``` vue
<vue-core-video-player @play="playFunc" loop :src="source" title="《Your Name》OST Sparkle" autoplay></vue-core-video-player>
```

[Events Reference](https://github.com/core-player/vue-core-video-player/blob/master/src/constants/EVENTS.js)
