### ISSUE TITLE
组件 name 不能设置为 switch

### ISSUE THREAD

**Issue by RRDAWLX** [core-player/vue-core-video-player#19]
vue给出了以下提示：
`Do not use built-in or reserved HTML elements as component id: switch`
项目中有这么个组件 src/widgets/switch.vue

**Comment by JackPu** [comment]
这是个警告，下个版本会 rename 这个组件。

**Comment by JackPu** [comment]
https://github.com/core-player/vue-core-video-player/pull/25 Close
