### ISSUE TITLE
[Vue warn]: Do not use built-in or reserved HTML elements as component id: switch

### ISSUE THREAD

**Issue by Agendum** [core-player/vue-core-video-player#22]
I am getting this console warning in Chrome:
[Vue warn]: Do not use built-in or reserved HTML elements as component id: switch

It is because this component is named 'switch':
https://github.com/core-player/vue-core-video-player/blob/master/src/widgets/switch.vue

Can you please rename it so we don't get this warning in the console?

**Comment by JackPu** [comment]
Version 0.1.8 has been released to fix the warning.
