### ISSUE TITLE
Error when mounting: Uncaught TypeError: Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by Agendum** [core-player/vue-core-video-player#24]
The full error is:

```text
Uncaught TypeError: Cannot read property 'open' of undefined
    at Object.<anonymous> (vue-core-video-player.common.js:7320)
    at Object.emit (vue-core-video-player.common.js:4156)
    at VueComponent.emit (vue-core-video-player.common.js:6511)
    at BaseVideoCore.emit (vue-core-video-player.common.js:6372)
    at vue-core-video-player.common.js:5954
```

FYI the current state of my view at the time is:

```
currentPanel = true
panelShow = false
speedListPanel = false
resolutionListPanel = false
resolution = '720p'
medias = ['string-to-my-mp4']
$container.classList = ['vcp-container', 'flex-grow-1']
```

After debugging I believe this is just a race condition or something in settings.vue:
https://github.com/core-player/vue-core-video-player/blob/master/src/dashboard/settings.vue

```javascript
  mounted () {
    this.on(EVENTS.SOURCE_UPDATED, () => {
      this.medias = this.$player.medias
      this.resolution = this.$player.resolution
      const { autoplay, loop } = this.$player.config
      if (autoplay) {
        this.$refs['autoplaySwitch'].open() // <-------- Error happens here
      }
      if (loop) {
        this.$refs['loopSwitch'].open()
      }
    })
    document.addEventListener('click', () => {
      if (this.panelShow) {
        this.panelShow = false
        this.speedListPanel = false
        this.resolutionListPanel = false
        this.$container.classList.remove('settings-open')
      }
    })
  }
```

If I turn off autoplay the error goes away.

Maybe it is also possible the object hasn't been constructed yet because perhaps of the v-show='panelShow' in the template?

Also I am concerned about the document.addEventListener in this code snippet. It is added during mounting, but never removed during unmounting. This means event listeners are being leaked in my application.

Thanks again for the great video player.

**Comment by JackPu** [comment]
@Agendum Tanks for your feedback. Can you show your source format and VUE code? I have tested your code case in my browser. It did not show any error?

**Comment by Agendum** [comment]
Unfortunately 0.1.8 made the problem much worse so I cannot upgrade. I am starting to think this is because I have the video player behind a v-if in a complex UX.

I am not at liberty to give the code for this. However I can set up a jsfiddle or something. Do you know how we can reference vue-core-video-player in jsfiddle.net?

**Comment by Agendum** [comment]
Here I made a quick simplified app which demonstrates the problem. In this app, click Show, and everything is great in the console. Click Hide. Click Show again and the video plays but vue-core-video-player is spewing tons of stuff in the console. Before it was just the 'open' error. I have the video player in a modal dialog which is popped open based on what was clicked, so the video player is a sub-component of a large hierarchy. Here is the app:

```vue
<template>
  <div id="app">
    <button @click="show = !show">{{show ? 'Hide' : 'Show'}}</button>
    <vue-core-video-player :src="videoSource" :loop="false" v-if="show"></vue-core-video-player>
  </div>
</template>

<script>
export default {
  name: 'app',
  data() {
    return {
      show: false,
      videoSource: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_1MB.mp4'
    };
  }
};
</script>
```

**Comment by Agendum** [comment]
@JackPu you closed this issue but I am not sure you get my last message. Should I open a new issue? Thanks.

**Comment by foufrix** [comment]
I can reproduce this bug. In my configuration Videoplayer is in a page and if you change page using vue-router and comeback to the video page it will throw lots of errors, same as @Agendum  

When you first arrive it work well but if you change page and come back to the videos page it will throw bugs and video will continue to play (similarity with what @Agendum said with show and hide that will probably trigger the same problem than changing page with vue-router)

![image](https://user-images.githubusercontent.com/16646581/82733609-335f9e80-9d15-11ea-97be-4fd24ed8a8bd.png)
