### ISSUE TITLE
如何自定义控制播放/暂停事件？

### ISSUE THREAD

**Issue by MaleWeb** [core-player/vue-core-video-player#32]
想要自己做一个控制组件，如果主动控制video的播放等Events？

**Comment by Moon1102** [comment]
> 想要自己做一个控制组件，如果主动控制video的播放等Events？

简单的说 加个ref 就可以拿到pause play方法 对全屏、音量等更细化的控制还是要研究一下

**Comment by JackPu** [comment]
目前是通过监听 play / pause 事件来弄得，如果你要控制的话，建议通过继承 videoCore 来自己实现一个播放内核

**Comment by rifkydj** [comment]
Can i have a sample code of customize control play/pause events ????
